//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinToolkitDLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinToolkitDLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BIOS {
            get {
                object obj = ResourceManager.GetObject("BIOS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] exe2cab {
            get {
                object obj = ResourceManager.GetObject("exe2cab", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap File_icon {
            get {
                object obj = ResourceManager.GetObject("File_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_48 {
            get {
                object obj = ResourceManager.GetObject("folder_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap process_icon {
            get {
                object obj = ResourceManager.GetObject("process_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DSAKeyValue&gt;
        ///  &lt;P&gt;lf1+/S+FrIBB5sles8+SkTpCQpeaX37Ykhb2YSa1lwN/xJxDZiSnzNKk3DfFHQP476PYNkJE2KxhwnJjO57TgVJBk1DtGdECgGk/y8N9pcYpIhIbyS4zBq0F6O8UJxLMWtpA7xfuDQqyOCn+XtBJUjmhyFYQ5hHqPrZmabhkF4M=&lt;/P&gt;
        ///  &lt;Q&gt;1nPbms7QwePgKZeh5uGKSVaYnqk=&lt;/Q&gt;
        ///  &lt;G&gt;lIu8+mI8WhZOwAaJ3g0ti838jtbvp+2/OlwstiKBUlAhGKqOWqZe25FLcfVMNc+ZaPxEcteAjkR/xVc6hFc8d887vehLHcFSjpLpgGKQwowhkdF3VNcWeRLiPGNWj5s3LYzwoRKtXPrpo8JW6HCXmTInlzeJRWFTGKBl4a0+hLA=&lt;/G&gt;
        ///  &lt;Y&gt;CljYzGor/YzsodJT/buPxNRToBiTssCGzWuC86DbBIjwpnBqUViJtcbj1yvYgvGpTE53p/6xNsookVOs4pAgTIJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string publicKey {
            get {
                return ResourceManager.GetString("publicKey", resourceCulture);
            }
        }
    }
}
